"""
PDF Export for SkyTrail Desktop
Generates beautiful astrology reports in PDF format
"""

import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, PageBreak, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas
import io

class PDFExporter:
    """Generate PDF reports from birth charts"""
    
    def __init__(self, chart, predictions=None, yogas=None, panchang=None, muhurta=None):
        self.chart = chart
        self.predictions = predictions or {}
        self.yogas = yogas or []
        self.panchang = panchang or {}
        self.muhurta = muhurta or {}
        self.styles = getSampleStyleSheet()
        self._setup_styles()
    
    def _setup_styles(self):
        """Setup custom styles for PDF"""
        self.styles.add(ParagraphStyle(
            name='Title',
            parent=self.styles['Heading1'],
            fontSize=24,
            alignment=TA_CENTER,
            spaceAfter=20,
            textColor=colors.HexColor('#1a237e')
        ))
        
        self.styles.add(ParagraphStyle(
            name='Subtitle',
            parent=self.styles['Heading2'],
            fontSize=14,
            alignment=TA_CENTER,
            spaceAfter=12,
            textColor=colors.HexColor('#283593')
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionTitle',
            parent=self.styles['Heading3'],
            fontSize=12,
            textColor=colors.HexColor('#0d47a1'),
            spaceAfter=8
        ))
        
        self.styles.add(ParagraphStyle(
            name='BodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#1a1a1a')
        ))
        
        self.styles.add(ParagraphStyle(
            name='PredictionText',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#2e7d32'),
            spaceAfter=4
        ))
    
    def generate_report(self, filename: str = None) -> str:
        """Generate complete PDF report"""
        if not filename:
            filename = f"SkyTrail_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
        doc = SimpleDocTemplate(
            filename,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        story = []
        
        # Cover Page
        story.extend(self._build_cover_page())
        story.append(PageBreak())
        
        # Chart Summary
        story.extend(self._build_chart_summary())
        story.append(PageBreak())
        
        # Planetary Positions
        story.extend(self._build_planet_positions())
        story.append(PageBreak())
        
        # Predictions
        story.extend(self._build_predictions())
        story.append(PageBreak())
        
        # Yogas
        if self.yogas:
            story.extend(self._build_yogas())
            story.append(PageBreak())
        
        # Panchang
        if self.panchang:
            story.extend(self._build_panchang())
            story.append(PageBreak())
        
        # Muhurta
        if self.muhurta:
            story.extend(self._build_muhurta())
        
        doc.build(story)
        return filename
    
    def _build_cover_page(self):
        """Build cover page"""
        story = []
        
        # Title
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph("SkyTrail", self.styles['Title']))
        story.append(Spacer(1, 12))
        story.append(Paragraph("Astrology Report", self.styles['Subtitle']))
        story.append(Spacer(1, 24))
        
        # Decorative line
        story.append(Paragraph("━" * 40, self.styles['Normal']))
        story.append(Spacer(1, 24))
        
        # Report details
        if self.chart:
            story.append(Paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}", self.styles['BodyText']))
            story.append(Paragraph(f"System: {self.chart.system.capitalize()}", self.styles['BodyText']))
            story.append(Paragraph(f"Ayanamsa: {self.chart.ayanamsa}", self.styles['BodyText']))
        
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph("Generated by SkyTrail Desktop", self.styles['BodyText']))
        
        return story
    
    def _build_chart_summary(self):
        """Build chart summary section"""
        story = []
        
        story.append(Paragraph("Chart Summary", self.styles['SectionTitle']))
        story.append(Spacer(1, 8))
        
        if self.chart:
            from translations import sign_name, nakshatra_name
            
            data = [
                ["Ascendant", f"{sign_name(self.chart.ascendant.sign_index, 'en')} {self.chart.ascendant.degree_in_sign:.1f}°"],
                ["System", self.chart.system.capitalize()],
                ["Ayanamsa", self.chart.ayanamsa],
            ]
            
            if self.chart.system == "vedic":
                data.append(["Nakshatra", f"{nakshatra_name(self.chart.nakshatra_index, 'en')} (Pada {self.chart.nakshatra_pada})"])
            
            if self.chart.dasha:
                data.append(["Current Dasha", f"{self.chart.dasha.get('current_dasha_name', 'Unknown')} ({self.chart.dasha.get('remaining_years', 0):.1f} years)"])
            
            table = Table(data, colWidths=[3*inch, 4*inch])
            table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#0d47a1')),
                ('TEXTCOLOR', (1, 0), (1, -1), colors.HexColor('#1a1a1a')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e3f2fd')),
            ]))
            
            story.append(table)
        
        return story
    
    def _build_planet_positions(self):
        """Build planetary positions table"""
        story = []
        
        story.append(Paragraph("Planetary Positions", self.styles['SectionTitle']))
        story.append(Spacer(1, 8))
        
        if self.chart:
            from translations import sign_name, planet_name
            
            data = [["Planet", "Sign", "Degree", "House", "Retrograde"]]
            
            for p in self.chart.planets:
                data.append([
                    planet_name(p.key, 'en'),
                    sign_name(p.sign_index, 'en'),
                    f"{p.degree_in_sign:.1f}°",
                    str(p.house),
                    "Yes" if p.retrograde else "No"
                ])
            
            table = Table(data, colWidths=[1.5*inch, 1.5*inch, 1.2*inch, 0.8*inch, 1.2*inch])
            table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0d47a1')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#1a1a1a')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f5f5f5')),
            ]))
            
            story.append(table)
        
        return story
    
    def _build_predictions(self):
        """Build predictions section"""
        story = []
        
        story.append(Paragraph("Astrological Predictions", self.styles['SectionTitle']))
        story.append(Spacer(1, 8))
        
        categories = ["Face", "Career", "Marriage", "Children", "Success", "Personality"]
        
        for category in categories:
            pred = self.predictions.get(category.lower(), {})
            if pred:
                story.append(Paragraph(f"🔮 {category}", self.styles['Subtitle']))
                story.append(Spacer(1, 4))
                
                for key, value in pred.items():
                    if key != "category":
                        key_display = key.replace('_', ' ').capitalize()
                        story.append(Paragraph(f"<b>{key_display}:</b> {value}", self.styles['BodyText']))
                
                story.append(Spacer(1, 8))
        
        return story
    
    def _build_yogas(self):
        """Build yogas section"""
        story = []
        
        story.append(Paragraph("🌟 Vedic Yogas Detected", self.styles['SectionTitle']))
        story.append(Spacer(1, 8))
        
        for yoga in self.yogas[:10]:
            story.append(Paragraph(f"<b>{yoga.name}</b>", self.styles['BodyText']))
            story.append(Paragraph(f"Type: {yoga.type} | Strength: {yoga.strength}", self.styles['BodyText']))
            story.append(Paragraph(yoga.description, self.styles['BodyText']))
            if yoga.planets:
                story.append(Paragraph(f"Planets: {', '.join(yoga.planets)}", self.styles['BodyText']))
            story.append(Spacer(1, 6))
        
        return story
    
    def _build_panchang(self):
        """Build panchang section"""
        story = []
        
        story.append(Paragraph("📅 Panchang", self.styles['SectionTitle']))
        story.append(Spacer(1, 8))
        
        if self.panchang:
            data = [
                ["Tithi", self.panchang.get('tithi', {}).get('name', 'Unknown')],
                ["Vara", self.panchang.get('vara', {}).get('name', 'Unknown')],
                ["Nakshatra", self.panchang.get('nakshatra', {}).get('name', 'Unknown')],
                ["Yoga", self.panchang.get('yoga', {}).get('name', 'Unknown')],
                ["Karana", self.panchang.get('karana', {}).get('name', 'Unknown')],
                ["Sunrise", self.panchang.get('sun', {}).get('rise', 'Unknown')],
                ["Sunset", self.panchang.get('sun', {}).get('set', 'Unknown')],
            ]
            
            table = Table(data, colWidths=[2.5*inch, 4.5*inch])
            table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#0d47a1')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            
            story.append(table)
        
        return story
    
    def _build_muhurta(self):
        """Build muhurta section"""
        story = []
        
        story.append(Paragraph("🎯 Muhurta", self.styles['SectionTitle']))
        story.append(Spacer(1, 8))
        
        if self.muhurta:
            story.append(Paragraph(f"<b>Event:</b> {self.muhurta.get('event_type', 'Unknown')}", self.styles['BodyText']))
            story.append(Paragraph(f"<b>Score:</b> {self.muhurta.get('score', 0)}/{self.muhurta.get('max_score', 0)}", self.styles['BodyText']))
            story.append(Paragraph(f"<b>Verdict:</b> {self.muhurta.get('verdict', 'Unknown')}", self.styles['BodyText']))
            story.append(Spacer(1, 8))
            
            if self.muhurta.get('details'):
                story.append(Paragraph("<b>Details:</b>", self.styles['BodyText']))
                for detail in self.muhurta['details']:
                    story.append(Paragraph(f"• {detail}", self.styles['BodyText']))
        
        return story